language: android
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew
  - tree

script:
  - ./gradlew clean --stacktrace
  - ./gradlew assemble --stacktrace
  - ./gradlew assembleRelease --stacktrace
checkout:
  post:
    - cp local.properties.ci local.properties
